// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiNibu.Data.Context.Oracle;

#nullable disable

namespace WebApiNibu.Data.Context.Oracle.Migrations
{
    [DbContext(typeof(OracleDbContext))]
    partial class OracleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("WebApiNibu.Data.Entity.CopaUpsa.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<decimal>("DetailPointA")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("DetailPointB")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("MatchStatusId")
                        .HasColumnType("int");

                    b.Property<int>("NumberMatch")
                        .HasColumnType("int");

                    b.Property<int>("ParticipationId")
                        .HasColumnType("int");

                    b.Property<decimal>("ScoreA")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("ScoreB")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MatchStatusId");

                    b.HasIndex("ParticipationId", "StartDate")
                        .HasDatabaseName("IX_Match_ParticipationId_StartDate");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.CopaUpsa.MatchStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MatchStatuses");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.CopaUpsa.Participation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.Property<int>("PhaseTypeId")
                        .HasColumnType("int");

                    b.Property<int>("SchoolId")
                        .HasColumnType("int");

                    b.Property<int>("SchoolTableId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PhaseTypeId");

                    b.HasIndex("SchoolTableId");

                    b.HasIndex("TournamentId");

                    b.ToTable("Participations");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.CopaUpsa.PhaseType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PhaseTypes");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.CopaUpsa.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)");

                    b.Property<int>("CoordX")
                        .HasColumnType("int");

                    b.Property<int>("CoordY")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.CopaUpsa.Roster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.Property<int>("PositionId")
                        .HasColumnType("int");

                    b.Property<int>("SchoolStudentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("PositionId");

                    b.HasIndex("SchoolStudentId");

                    b.ToTable("Rosters");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.CopaUpsa.Sport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Sports");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.CopaUpsa.Statistic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("SportId")
                        .HasColumnType("int");

                    b.Property<int>("StatisticType")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SportId");

                    b.ToTable("Statistics");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.CopaUpsa.StatisticEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("Moment")
                        .HasColumnType("time(6)");

                    b.Property<int>("RosterId")
                        .HasColumnType("int");

                    b.Property<int>("StatisticId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RosterId");

                    b.HasIndex("StatisticId");

                    b.ToTable("StatisticEvents");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.CopaUpsa.Tournament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Banner")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("HasGroupStage")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("HasPlayOffStage")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Icon")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<string>("Logo")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("SportId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("TournamentParentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SportId");

                    b.HasIndex("TournamentParentId", "SportId")
                        .HasDatabaseName("IX_Tournament_ParentId_SportId");

                    b.ToTable("Tournaments");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.CopaUpsa.TournamentParent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TournamentParents");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.Feed.Events.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Asistencia")
                        .HasColumnType("int");

                    b.Property<string>("BannerImageUrl")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<string>("CargoCorres1")
                        .HasColumnType("longtext");

                    b.Property<string>("CargoCorres2")
                        .HasColumnType("longtext");

                    b.Property<string>("Cargores")
                        .HasColumnType("longtext");

                    b.Property<string>("Corresponsable1")
                        .HasColumnType("longtext");

                    b.Property<string>("Corresponsable2")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FeedImageUrl")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<int>("IdEstado")
                        .HasColumnType("int");

                    b.Property<int>("IdTipo")
                        .HasColumnType("int");

                    b.Property<int>("IdUbicacion")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Observacion")
                        .HasColumnType("longtext");

                    b.Property<string>("Qr")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Unidad")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IsFeatured")
                        .HasDatabaseName("IX_Event_IsFeatured");

                    b.HasIndex("StartDate")
                        .HasDatabaseName("IX_Event_StartDate");

                    b.ToTable("Event");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.Feed.Events.EventDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("BlockNumber")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("EventDetail");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.Feed.Events.EventInteraction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("IdColegio")
                        .HasColumnType("int");

                    b.Property<int>("IdEstudiante")
                        .HasColumnType("int");

                    b.Property<bool>("IsAttending")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("MerchId")
                        .HasColumnType("int");

                    b.Property<string>("NombreHermano")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Origen")
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)");

                    b.Property<int?>("QrAccessId")
                        .HasColumnType("int");

                    b.Property<int?>("QrId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("MerchId");

                    b.HasIndex("QrAccessId");

                    b.HasIndex("UserId");

                    b.ToTable("EventInteraction");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.Feed.News.News", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("BannerImageUrl")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("FeedImageUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_News_PublicationDate");

                    b.ToTable("News");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.Feed.News.NewsDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("BlockNumber")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("NewsId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NewsId");

                    b.ToTable("NewsDetail");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.Feed.News.NewsReaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("MerchId")
                        .HasColumnType("int");

                    b.Property<int>("NewsId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MerchId");

                    b.HasIndex("NewsId");

                    b.HasIndex("UserId");

                    b.ToTable("NewsReaction");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.Feed.Polls.Option", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Correct")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ParticipationId")
                        .HasColumnType("int");

                    b.Property<int>("PollId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParticipationId");

                    b.HasIndex("PollId");

                    b.ToTable("Option");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.Feed.Polls.Poll", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId");

                    b.ToTable("Poll");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.Feed.Polls.SelectedOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("OptionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OptionId");

                    b.HasIndex("UserId");

                    b.ToTable("SelectedOption");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.Person.AcademicPreferenceImpl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("IdCarreer")
                        .HasColumnType("int");

                    b.Property<int>("IdPreferencesStudent")
                        .HasColumnType("int");

                    b.Property<int>("IdUniversitiy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdCarreer");

                    b.HasIndex("IdPreferencesStudent");

                    b.HasIndex("IdUniversitiy");

                    b.ToTable("AcademicPreferenceImpl");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.Person.AdultType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AdultType");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.Person.Carreer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("AreaFormacionId")
                        .HasColumnType("int");

                    b.Property<string>("BannerImage")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<int>("CodCarrRel")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("OrdenEventos")
                        .HasColumnType("int");

                    b.Property<int?>("UniversityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UniversityId");

                    b.ToTable("Carreer");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.Person.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Country");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.Person.DocumentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DocumentType");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.Person.InterestActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("InterestActivity");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.Person.Merch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<string>("Icon")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<int>("IdMerchType")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<int>("MaxQuantity")
                        .HasColumnType("int");

                    b.Property<int>("MerchTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<int>("Rarity")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MerchTypeId");

                    b.ToTable("Merch");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.Person.MerchObtention", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Claimed")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("IdMerch")
                        .HasColumnType("int");

                    b.Property<int>("IdSchoolStudent")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdMerch");

                    b.HasIndex("IdSchoolStudent");

                    b.ToTable("MerchObtention");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.Person.MerchType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MerchType");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.Person.PersonTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("IdCountry")
                        .HasColumnType("int");

                    b.Property<int>("IdDocumentType")
                        .HasColumnType("int");

                    b.Property<string>("MaternalSurname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PaternalSurname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PersonType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdCountry");

                    b.HasIndex("IdDocumentType");

                    b.ToTable("personTable", (string)null);

                    b.HasDiscriminator<string>("PersonType").HasValue("PersonTable");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.Person.PreferencesStudent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("HaveVocationalTest")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("IdSchoolStudent")
                        .HasColumnType("int");

                    b.Property<int>("LevelInformation")
                        .HasColumnType("int");

                    b.Property<bool>("StudyAbroad")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<int>("WhereHadTest")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdSchoolStudent");

                    b.ToTable("PreferencesStudent");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.Person.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.Person.StudentInterest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("IdInterestActivity")
                        .HasColumnType("int");

                    b.Property<int>("IdSchoolStudent")
                        .HasColumnType("int");

                    b.Property<string>("Moment")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<int>("MomentSelected")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdInterestActivity");

                    b.HasIndex("IdSchoolStudent");

                    b.ToTable("StudentInterest");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.Person.University", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Dpto")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<int?>("IdEventos")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<string>("NivelCompetencia")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("OrdenEventos")
                        .HasColumnType("int");

                    b.Property<string>("Sigla")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("University");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.School.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("PersonEmail")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("PersonName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("PersonPhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("PersonRole")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("SchoolTableId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SchoolTableId");

                    b.ToTable("Contact");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.School.SchoolTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Delegada")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("IdColegio")
                        .HasColumnType("int");

                    b.Property<int>("IdDelegada")
                        .HasColumnType("int");

                    b.Property<int>("IdDepartamento")
                        .HasColumnType("int");

                    b.Property<int>("Ka")
                        .HasColumnType("int");

                    b.Property<int>("KaRectorada")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("NormalLogo")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("Rue")
                        .HasColumnType("int");

                    b.Property<string>("Segemento")
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.Property<string>("SportLogo")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SchoolTable");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.Tags.EventTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("TagId");

                    b.ToTable("EventTags");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.Tags.NewsTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("NewsId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NewsId");

                    b.HasIndex("TagId");

                    b.ToTable("NewsTags");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.Tags.NotifyTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("NotifyType")
                        .HasColumnType("int");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TagId");

                    b.HasIndex("UserId");

                    b.ToTable("NotifyTag");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.Tags.PollTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PollId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PollId");

                    b.HasIndex("TagId");

                    b.ToTable("PollTags");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.Tags.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Group")
                        .HasDatabaseName("IX_Tag_Group");

                    b.ToTable("Tag");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.UsersAndAccess.QrAccess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Reason")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("QrAccess");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.UsersAndAccess.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("IdPerson")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)");

                    b.Property<string>("ProfilePhoto")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdPerson")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_IdPerson");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Users_Name");

                    b.ToTable("users");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.Person.Adult", b =>
                {
                    b.HasBaseType("WebApiNibu.Data.Entity.Person.PersonTable");

                    b.Property<int>("IdAdultType")
                        .HasColumnType("int");

                    b.Property<int>("IdSchoolStudent")
                        .HasColumnType("int");

                    b.Property<string>("WorkEmail")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("WorkPhoneNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasIndex("IdAdultType");

                    b.HasIndex("IdSchoolStudent");

                    b.ToTable("personTable", (string)null);

                    b.HasDiscriminator().HasValue("Adult");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.Person.SchoolStudent", b =>
                {
                    b.HasBaseType("WebApiNibu.Data.Entity.Person.PersonTable");

                    b.Property<bool>("HasUpsaParents")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("IdSchool")
                        .HasColumnType("int");

                    b.Property<bool>("IsPlayer")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("SchoolGrade")
                        .HasColumnType("int");

                    b.HasIndex("IdSchool");

                    b.ToTable("personTable", (string)null);

                    b.HasDiscriminator().HasValue("SchoolStudent");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.Person.Worker", b =>
                {
                    b.HasBaseType("WebApiNibu.Data.Entity.Person.PersonTable");

                    b.Property<int>("IdRole")
                        .HasColumnType("int");

                    b.Property<string>("WorkEmail")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.HasIndex("IdRole");

                    b.ToTable("personTable", null, t =>
                        {
                            t.Property("WorkEmail")
                                .HasColumnName("Worker_WorkEmail");
                        });

                    b.HasDiscriminator().HasValue("Worker");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.CopaUpsa.Match", b =>
                {
                    b.HasOne("WebApiNibu.Data.Entity.CopaUpsa.MatchStatus", "MatchStatus")
                        .WithMany("Matches")
                        .HasForeignKey("MatchStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApiNibu.Data.Entity.CopaUpsa.Participation", "Participation")
                        .WithMany("Matches")
                        .HasForeignKey("ParticipationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MatchStatus");

                    b.Navigation("Participation");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.CopaUpsa.Participation", b =>
                {
                    b.HasOne("WebApiNibu.Data.Entity.CopaUpsa.PhaseType", "PhaseType")
                        .WithMany("Participations")
                        .HasForeignKey("PhaseTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApiNibu.Data.Entity.School.SchoolTable", "SchoolTable")
                        .WithMany("Participations")
                        .HasForeignKey("SchoolTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApiNibu.Data.Entity.CopaUpsa.Tournament", "Tournament")
                        .WithMany("Participations")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PhaseType");

                    b.Navigation("SchoolTable");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.CopaUpsa.Roster", b =>
                {
                    b.HasOne("WebApiNibu.Data.Entity.CopaUpsa.Match", "Match")
                        .WithMany("Rosters")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApiNibu.Data.Entity.CopaUpsa.Position", "Position")
                        .WithMany("Rosters")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApiNibu.Data.Entity.Person.SchoolStudent", "SchoolStudent")
                        .WithMany()
                        .HasForeignKey("SchoolStudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Position");

                    b.Navigation("SchoolStudent");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.CopaUpsa.Statistic", b =>
                {
                    b.HasOne("WebApiNibu.Data.Entity.CopaUpsa.Sport", "Sport")
                        .WithMany()
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sport");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.CopaUpsa.StatisticEvent", b =>
                {
                    b.HasOne("WebApiNibu.Data.Entity.CopaUpsa.Roster", "Roster")
                        .WithMany("StatisticEvents")
                        .HasForeignKey("RosterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApiNibu.Data.Entity.CopaUpsa.Statistic", "Statistic")
                        .WithMany("StatisticEvents")
                        .HasForeignKey("StatisticId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Roster");

                    b.Navigation("Statistic");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.CopaUpsa.Tournament", b =>
                {
                    b.HasOne("WebApiNibu.Data.Entity.CopaUpsa.Sport", "Sport")
                        .WithMany("Tournaments")
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApiNibu.Data.Entity.CopaUpsa.TournamentParent", "TournamentParent")
                        .WithMany("Tournaments")
                        .HasForeignKey("TournamentParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sport");

                    b.Navigation("TournamentParent");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.Feed.Events.EventDetail", b =>
                {
                    b.HasOne("WebApiNibu.Data.Entity.Feed.Events.Event", "Event")
                        .WithMany("EventDetails")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.Feed.Events.EventInteraction", b =>
                {
                    b.HasOne("WebApiNibu.Data.Entity.Feed.Events.Event", "Event")
                        .WithMany("EventInteractions")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApiNibu.Data.Entity.Person.Merch", "Merch")
                        .WithMany()
                        .HasForeignKey("MerchId");

                    b.HasOne("WebApiNibu.Data.Entity.UsersAndAccess.QrAccess", "QrAccess")
                        .WithMany()
                        .HasForeignKey("QrAccessId");

                    b.HasOne("WebApiNibu.Data.Entity.UsersAndAccess.Users", "User")
                        .WithMany("EventInteracts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Merch");

                    b.Navigation("QrAccess");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.Feed.News.NewsDetail", b =>
                {
                    b.HasOne("WebApiNibu.Data.Entity.Feed.News.News", "News")
                        .WithMany("NewsDetails")
                        .HasForeignKey("NewsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("News");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.Feed.News.NewsReaction", b =>
                {
                    b.HasOne("WebApiNibu.Data.Entity.Person.Merch", "Merch")
                        .WithMany()
                        .HasForeignKey("MerchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApiNibu.Data.Entity.Feed.News.News", "News")
                        .WithMany("NewsReactions")
                        .HasForeignKey("NewsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApiNibu.Data.Entity.UsersAndAccess.Users", "User")
                        .WithMany("NewsReactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Merch");

                    b.Navigation("News");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.Feed.Polls.Option", b =>
                {
                    b.HasOne("WebApiNibu.Data.Entity.CopaUpsa.Participation", "Participation")
                        .WithMany("Options")
                        .HasForeignKey("ParticipationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApiNibu.Data.Entity.Feed.Polls.Poll", "Poll")
                        .WithMany("Options")
                        .HasForeignKey("PollId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Participation");

                    b.Navigation("Poll");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.Feed.Polls.Poll", b =>
                {
                    b.HasOne("WebApiNibu.Data.Entity.CopaUpsa.Tournament", "Tournament")
                        .WithMany()
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.Feed.Polls.SelectedOption", b =>
                {
                    b.HasOne("WebApiNibu.Data.Entity.Feed.Polls.Option", "Option")
                        .WithMany("SelectedOptions")
                        .HasForeignKey("OptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApiNibu.Data.Entity.UsersAndAccess.Users", "User")
                        .WithMany("SelectedOptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Option");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.Person.AcademicPreferenceImpl", b =>
                {
                    b.HasOne("WebApiNibu.Data.Entity.Person.Carreer", "Carreer")
                        .WithMany("AcademicPreferences")
                        .HasForeignKey("IdCarreer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApiNibu.Data.Entity.Person.PreferencesStudent", "PreferencesStudent")
                        .WithMany("AcademicPreferences")
                        .HasForeignKey("IdPreferencesStudent")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApiNibu.Data.Entity.Person.University", "Universitiy")
                        .WithMany("AcademicPreferences")
                        .HasForeignKey("IdUniversitiy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carreer");

                    b.Navigation("PreferencesStudent");

                    b.Navigation("Universitiy");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.Person.Carreer", b =>
                {
                    b.HasOne("WebApiNibu.Data.Entity.Person.University", "University")
                        .WithMany("Carreers")
                        .HasForeignKey("UniversityId");

                    b.Navigation("University");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.Person.Merch", b =>
                {
                    b.HasOne("WebApiNibu.Data.Entity.Person.MerchType", "MerchType")
                        .WithMany("Merches")
                        .HasForeignKey("MerchTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MerchType");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.Person.MerchObtention", b =>
                {
                    b.HasOne("WebApiNibu.Data.Entity.Person.Merch", "Merch")
                        .WithMany("MerchObtentions")
                        .HasForeignKey("IdMerch")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApiNibu.Data.Entity.Person.SchoolStudent", "SchoolStudent")
                        .WithMany("MerchObtentions")
                        .HasForeignKey("IdSchoolStudent")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Merch");

                    b.Navigation("SchoolStudent");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.Person.PersonTable", b =>
                {
                    b.HasOne("WebApiNibu.Data.Entity.Person.Country", "Country")
                        .WithMany("People")
                        .HasForeignKey("IdCountry")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApiNibu.Data.Entity.Person.DocumentType", "DoucmentType")
                        .WithMany("People")
                        .HasForeignKey("IdDocumentType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("DoucmentType");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.Person.PreferencesStudent", b =>
                {
                    b.HasOne("WebApiNibu.Data.Entity.Person.SchoolStudent", "SchoolStudent")
                        .WithMany("PreferencesStudents")
                        .HasForeignKey("IdSchoolStudent")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SchoolStudent");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.Person.StudentInterest", b =>
                {
                    b.HasOne("WebApiNibu.Data.Entity.Person.InterestActivity", "InterestActivity")
                        .WithMany("StudentInterests")
                        .HasForeignKey("IdInterestActivity")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApiNibu.Data.Entity.Person.SchoolStudent", "SchoolStudent")
                        .WithMany("StudentInterests")
                        .HasForeignKey("IdSchoolStudent")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InterestActivity");

                    b.Navigation("SchoolStudent");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.School.Contact", b =>
                {
                    b.HasOne("WebApiNibu.Data.Entity.School.SchoolTable", "SchoolTable")
                        .WithMany("Contacts")
                        .HasForeignKey("SchoolTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SchoolTable");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.Tags.EventTag", b =>
                {
                    b.HasOne("WebApiNibu.Data.Entity.Feed.Events.Event", "News")
                        .WithMany("EventTags")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApiNibu.Data.Entity.Tags.Tag", "Tag")
                        .WithMany("EventTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("News");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.Tags.NewsTag", b =>
                {
                    b.HasOne("WebApiNibu.Data.Entity.Feed.News.News", "News")
                        .WithMany("NewsTags")
                        .HasForeignKey("NewsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApiNibu.Data.Entity.Tags.Tag", "Tag")
                        .WithMany("NewsTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("News");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.Tags.NotifyTag", b =>
                {
                    b.HasOne("WebApiNibu.Data.Entity.Tags.Tag", "Tag")
                        .WithMany("NotifyTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApiNibu.Data.Entity.UsersAndAccess.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.Tags.PollTag", b =>
                {
                    b.HasOne("WebApiNibu.Data.Entity.Feed.Polls.Poll", "Poll")
                        .WithMany("PollTags")
                        .HasForeignKey("PollId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApiNibu.Data.Entity.Tags.Tag", "Tag")
                        .WithMany("PollTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Poll");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.UsersAndAccess.Users", b =>
                {
                    b.HasOne("WebApiNibu.Data.Entity.Person.PersonTable", "PersonTable")
                        .WithOne("User")
                        .HasForeignKey("WebApiNibu.Data.Entity.UsersAndAccess.Users", "IdPerson")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PersonTable");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.Person.Adult", b =>
                {
                    b.HasOne("WebApiNibu.Data.Entity.Person.AdultType", "AdultType")
                        .WithMany("Adults")
                        .HasForeignKey("IdAdultType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApiNibu.Data.Entity.Person.SchoolStudent", "SchoolStudent")
                        .WithMany("Adults")
                        .HasForeignKey("IdSchoolStudent")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdultType");

                    b.Navigation("SchoolStudent");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.Person.SchoolStudent", b =>
                {
                    b.HasOne("WebApiNibu.Data.Entity.School.SchoolTable", "SchoolTable")
                        .WithMany("SchoolStudents")
                        .HasForeignKey("IdSchool")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SchoolTable");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.Person.Worker", b =>
                {
                    b.HasOne("WebApiNibu.Data.Entity.Person.Role", "Role")
                        .WithMany("Workers")
                        .HasForeignKey("IdRole")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.CopaUpsa.Match", b =>
                {
                    b.Navigation("Rosters");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.CopaUpsa.MatchStatus", b =>
                {
                    b.Navigation("Matches");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.CopaUpsa.Participation", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("Options");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.CopaUpsa.PhaseType", b =>
                {
                    b.Navigation("Participations");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.CopaUpsa.Position", b =>
                {
                    b.Navigation("Rosters");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.CopaUpsa.Roster", b =>
                {
                    b.Navigation("StatisticEvents");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.CopaUpsa.Sport", b =>
                {
                    b.Navigation("Tournaments");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.CopaUpsa.Statistic", b =>
                {
                    b.Navigation("StatisticEvents");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.CopaUpsa.Tournament", b =>
                {
                    b.Navigation("Participations");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.CopaUpsa.TournamentParent", b =>
                {
                    b.Navigation("Tournaments");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.Feed.Events.Event", b =>
                {
                    b.Navigation("EventDetails");

                    b.Navigation("EventInteractions");

                    b.Navigation("EventTags");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.Feed.News.News", b =>
                {
                    b.Navigation("NewsDetails");

                    b.Navigation("NewsReactions");

                    b.Navigation("NewsTags");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.Feed.Polls.Option", b =>
                {
                    b.Navigation("SelectedOptions");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.Feed.Polls.Poll", b =>
                {
                    b.Navigation("Options");

                    b.Navigation("PollTags");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.Person.AdultType", b =>
                {
                    b.Navigation("Adults");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.Person.Carreer", b =>
                {
                    b.Navigation("AcademicPreferences");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.Person.Country", b =>
                {
                    b.Navigation("People");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.Person.DocumentType", b =>
                {
                    b.Navigation("People");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.Person.InterestActivity", b =>
                {
                    b.Navigation("StudentInterests");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.Person.Merch", b =>
                {
                    b.Navigation("MerchObtentions");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.Person.MerchType", b =>
                {
                    b.Navigation("Merches");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.Person.PersonTable", b =>
                {
                    b.Navigation("User");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.Person.PreferencesStudent", b =>
                {
                    b.Navigation("AcademicPreferences");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.Person.Role", b =>
                {
                    b.Navigation("Workers");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.Person.University", b =>
                {
                    b.Navigation("AcademicPreferences");

                    b.Navigation("Carreers");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.School.SchoolTable", b =>
                {
                    b.Navigation("Contacts");

                    b.Navigation("Participations");

                    b.Navigation("SchoolStudents");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.Tags.Tag", b =>
                {
                    b.Navigation("EventTags");

                    b.Navigation("NewsTags");

                    b.Navigation("NotifyTags");

                    b.Navigation("PollTags");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.UsersAndAccess.Users", b =>
                {
                    b.Navigation("EventInteracts");

                    b.Navigation("NewsReactions");

                    b.Navigation("SelectedOptions");
                });

            modelBuilder.Entity("WebApiNibu.Data.Entity.Person.SchoolStudent", b =>
                {
                    b.Navigation("Adults");

                    b.Navigation("MerchObtentions");

                    b.Navigation("PreferencesStudents");

                    b.Navigation("StudentInterests");
                });
#pragma warning restore 612, 618
        }
    }
}
